drop database restate;
create database restate;

\c restate

CREATE TABLE CUSTOMER (	
	C_id VARCHAR(40) NOT NULL,
	Fname VARCHAR(40) NOT NULL,
	Lname VARCHAR(40) NOT NULL, 
	Bdate DATE, 
	Gender CHAR,
	Phone VARCHAR(12),
	email VARCHAR(40),
	Address	VARCHAR(40),
	PRIMARY KEY (C_id)
	);
	
CREATE TABLE PLOT (	
	P_id INT NOT NULL,
	s_id VARCHAR(40) NOT NULL,
	Location VARCHAR(40) NOT NULL,
	Locality VARCHAR(40) NOT NULL, 
	Area INT NOT NULL,
	Available BOOLEAN NOT NULL,
	costpersqft INT NOT NULL,
	PRIMARY KEY (P_id),
	FOREIGN KEY (s_id) REFERENCES CUSTOMER(c_id)
	);

CREATE TABLE PROPERTY (	
	P_id INT NOT NULL,
	s_id VARCHAR(40) NOT NULL,
	Location VARCHAR(40) NOT NULL,
	Locality VARCHAR(40) NOT NULL, 
	Area INT NOT NULL,
	Available BOOLEAN NOT NULL,
	Ptype VARCHAR(20) NOT NULL,
	price INT NOT NULL,
	PRIMARY KEY (P_id),
	FOREIGN KEY (s_id) REFERENCES CUSTOMER(c_id)
	);

CREATE TABLE FACILITIES (
  	P_id INT NOT NULL,
	Security BOOLEAN NOT NULL,
	Gym BOOLEAN NOT NULL,
	Pool BOOLEAN NOT NULL,
	Plumber BOOLEAN NOT NULL,
	Electrician BOOLEAN NOT NULL,
	PRIMARY KEY (P_id),
	FOREIGN KEY (P_id) REFERENCES PROPERTY(P_id) ON DELETE CASCADE
	);


CREATE TABLE PLOTREGISTRATION (
	id INT NOT NULL,
	Rcustomer_id VARCHAR(40) NOT NULL,
	Rtype VARCHAR(40) NOT NULL, 
	Rfor VARCHAR(40) NOT NULL,	--Buy/sell--
	PRIMARY KEY (id),
	FOREIGN KEY (id) REFERENCES PLOT(P_id),
	FOREIGN KEY (Rcustomer_id) REFERENCES CUSTOMER(C_id) ON DELETE CASCADE
	);

CREATE TABLE PROPREGISTRATION (
	id INT NOT NULL,
	Rcustomer_id VARCHAR(40) NOT NULL,
	Rtype VARCHAR(40) NOT NULL, 
	Rfor VARCHAR(40) NOT NULL,	--Buy/sell--
	PRIMARY KEY (id),
	FOREIGN KEY (id) REFERENCES PROPERTY(P_id),
	FOREIGN KEY (Rcustomer_id) REFERENCES CUSTOMER(C_id) ON DELETE CASCADE
	);

CREATE TABLE RENT (	
	P_id INT NOT NULL,
	rent_per_month INT NOT NULL,
	rating INT, --out of 10-- 
	CautionDeposit INT NOT NULL,
	PRIMARY KEY (P_id), 
	FOREIGN KEY (P_id) REFERENCES PROPERTY(P_id) ON DELETE CASCADE
	);

/*CREATE TABLE BUY (	
	PropID INT,
	PlotID INT,
	costpersqft INT NOT NULL,
	rating INT --out of 10-- 
	FOREIGN KEY (Prop_id) REFERENCES PROPERTY(P_id) ON DELETE CASCADE,
	FOREIGN KEY (Plot_id) REFERENCES PLOT(P_id) ON DELETE CASCADE
	);*/
	
CREATE TABLE LOGIN (
	username VARCHAR(20),
	password VARCHAR(20),
	PRIMARY KEY (username),
	FOREIGN KEY (username) REFERENCES CUSTOMER(c_id) ON DELETE CASCADE
);